---
DEFAULT_VALUE:
  APPIUM_SERVER_IP: "0.0.0.0"
  PORT: 4723
  IOS_WDA_PORT: 8100
MONKEY:
  HOME_KEY_RATIO: 1
  LONG_PRESS_RATIO: 1
  DRAG_RATIO: 5
  DOUBLE_TAP_RATIO: 5
  RESTART_APP_RATIO: 0
  PINCH_RATIO: 5
  CLICK_RATIO: 70
  CLICK_SPECIAL_POINT_RATIO: 4
  BACK_KEY_RATIO: 1
  SWIPE_RATIO: 4
  UNPINCH_RATIO: 5
LOGIN_ELEMENTS:
  LOGIN_ELEMENTS_ANDROID:
  - loginChange:
      xpath: "//*[@resource-id=\"com.xes.jazhanghui.activity:id/login_change\"]"
      action: "click"
  - username:
      xpath: "//android.widget.TextView[contains(@text, '请输入手机号')]"
      action: "input"
      value: "18600753024"
  - password:
      xpath: "//android.widget.TextView[contains(@text, '请输入密码')]"
      action: "input"
      value: "123456"
  - loginButton:
      xpath: "//android.widget.TextView[contains(@text, '登录')]"
      action: "click"
  LOGIN_ELEMENTS_IOS:
  - IOS_USERNAME:
      XPATH: "//*[@type=\"XCUIElementTypeTextField\"]"
      ACTION: "input"
      VALUE: "13691034108"
  - IOS_PASSWORD:
      XPATH: "//*[@type=\"XCUIElementTypeSecureTextField\" and @value=\"请输入登录密码\"]"
      ACTION: "input"
      VALUE: "123456"
  - IOS_LOGIN_BUTTON:
      XPATH: "//*[@type=\"XCUIElementTypeButton\" and @name=\"登录\" and @label=\"登录\
        \"]"
      ACTION: "click"
  - DRAG:
      XPATH: "//*[@resource-id=\"com.xes.jazhanghui.activity:id/xes_login_username\"\
        ]"
      ACTION: "drag"
      VALUE: "250,1050,800,1050,800,1550"
LOG:
  DB_LOG: false
  DOM_DISPLAY: false
  PERF_LOG: false
CRITICAL_ELEMENT:
  IOS_IPA_NAME: "wechat"
  ANDROID_CLICK_XPATH_HEADER: " ( string-length(@text)<30  or contains(@text,\"允许\"\
    ) ) "
  IOS_BUNDLE_NAME: "微信"
  ANDROID_PACKAGE: "com.xes.jazhanghui.activity"
  ANDROID_BOTTOM_TAB_BAR_ID: "@resource-id=\"com.huxiu:id/footer_bar\""
  IOS_BOTTOM_TAB_BAR_TYPE: "XCUIElementTypeTabBar"
  IOS_CLICK_XPATH_HEADER: "@visible=\"true\" and string-length(@value)<30"
  ANDROID_MAIN_ACTIVITY: "com.xes.jazhanghui.activity.mvp.start.StartActivity"
  IOS_BUNDLE_ID: "com.tencent.xin"
MINI_PROGRAM:
  MINI_PROGRAM_PROCESS: "com.tencent.mm:appbrand1"
  MINI_PROGRAM_NAME: "学而思营业厅"
INFLUXDB:
  DB_PORT: 8086
  DB_IP: "localhost"
d6744554:
  DEVICE_NAME: "XiaoMi4"
MONKEY_LIST:
  LONG_PRESS_LIST:
  - "980,560"
  - "100,250"
  MONKEY_SPECIAL_POINT_LIST:
  - "80,160"
  - "50,50"
  MONKEY_BLACKLIST_POINT_LIST:
  - "radius,10"
  - "0,0"
GENERAL:
  CRASH_PIC_COUNT: 10
  DEFAULT_WAIT_SEC: 10
  ENABLE_VERTICAL_SWIPE: false
  MAX_CLICK_COUNT: 100000
  MAX_DEPTH: 10
  SCREENSHOT_COUNT: 1000
  DEFAULT_POLLING_INTERVAL_SEC: 5
  CRAWLER_RUNNING_TIME: 60
  VIDEO_VERTICAL: true
  IGNORE_CRASH: true
  REMOVE_BOTTOM_BOUND: false
LIST:
  ITEM_BLACKLIST:
  - "客服"
  - "电话"
  - "不允许"
  - "拒绝"
  - "拍照"
  - "禁止"
  - "呼叫"
  - "低电量模式"
  - "关闭"
  - "去付款"
  INPUT_TEXT_LIST:
  - "123"
  - "asc"
  - "mkis"
  ITEM_WHITE_LIST:
  - "确定"
  - "允许"
  - "退出"
  - "取消"
  - "已解决"
  ANDROID_EXCLUDE_TYPE:
  - "android.widget.FrameLayout"
  - "android.widget.ImageButton"
  IOS_VALID_BUNDLE_LIST:
  - "照片"
  STRUCTURE_NODE_NAME_EXCLUDE_LIST:
  - "name"
  - "text"
  PRESS_BACK_KEY_PACKAGE_LIST:
  - "高德地图"
  - "com.autonavi.minimap"
  - "com.android.settings"
  NODE_NAME_EXCLUDE_LIST:
  - "selected"
  - "instance"
  - "checked"
  - "naf"
  - "content"
  IOS_EXCLUDE_TYPE:
  - "XCUIElementTypeOther"
  - "XCUIElementTypeKey"
  - "XCUIElementTypeWindow"
  - "XCUIElementTypeApplication"
  INPUT_CLASS_LIST:
  - "android.widget.TextView"
  - "XCUIElementTypeTextField"
  - "XCUIElementTypeSecureTextField"
  BACK_KEY_TRIGGER_LIST:
  - "回退"
  - "back"
  - "return"
  ANDROID_VALID_PACKAGE_LIST:
  - "com.miui.securitycenter"
  - "com.android.server.telecom"
  - "com.lbe.security.miui"
  - "gallery"
  - "packageinstaller"
  IOS_EXCLUDE_BAR:
  - "XCUIElementTypeStatusBar"
  - "XCUIElementTypeKeyboard"
